-- MySQL Workbench Synchronization
-- Generated: 2017-04-25 16:30
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: jonat

CREATE TABLE IF NOT EXISTS Unidade (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Nome VARCHAR(255) NOT NULL,
  CNPJ VARCHAR(30) NOT NULL,
  Enabled BOOLEAN NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE INDEX ID_UNIQUE (ID ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS Funcionario (
  ID INT NOT NULL AUTO_INCREMENT,
  Nome VARCHAR(255) NOT NULL,
  Login VARCHAR(20) NOT NULL,
  Senha VARCHAR(15) NOT NULL,
  Cargo VARCHAR(50) NOT NULL,
  Admissao DATE NOT NULL,
  Alterado_Em TIMESTAMP NOT NULL,
  CTPS VARCHAR(45) NOT NULL,
  Enabled BOOLEAN NOT NULL,
  ID_Unidade INT(11) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE INDEX ID_UNIQUE (ID ASC),
  UNIQUE INDEX Login_UNIQUE (Login ASC),
  UNIQUE INDEX CTPS_UNIQUE (CTPS ASC),
  UNIQUE INDEX ID_Unidade_UNIQUE (ID_Unidade ASC),
  CONSTRAINT
    FOREIGN KEY (ID_Unidade)
    REFERENCES Unidade (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS Cliente (
  CPF VARCHAR(11) NOT NULL,
  Nome VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NULL DEFAULT NULL,
  Telefone VARCHAR(45) NULL DEFAULT NULL,
  Enabled BOOLEAN NOT NULL,
  UNIQUE INDEX ID_UNIQUE (CPF ASC),
  PRIMARY KEY (CPF))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS Servico (
  ID INT NOT NULL AUTO_INCREMENT,
  Nome VARCHAR(255) NOT NULL,
  Preco DOUBLE NOT NULL,
  Enabled BOOLEAN NOT NULL,
  Unidade INT NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE INDEX ID_UNIQUE (ID ASC),
  INDEX ID_Unidade_idx (Unidade ASC),
  CONSTRAINT ID_Unidade
    FOREIGN KEY (Unidade)
    REFERENCES Unidade (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS Venda (
  ID INT NOT NULL AUTO_INCREMENT,
  CPF_Cliente VARCHAR(11) NOT NULL,
  ID_Funcionario INT NOT NULL,
  Data DATE NOT NULL,
  Total DOUBLE NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE INDEX ID_UNIQUE (ID ASC),
  INDEX CPF_idx (CPF_Cliente ASC),
  INDEX Funcionario_idx (ID_Funcionario ASC),
  CONSTRAINT CPF
    FOREIGN KEY (CPF_Cliente)
    REFERENCES Cliente (CPF)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT Funcionario
    FOREIGN KEY (ID_Funcionario)
    REFERENCES Funcionario (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS ServicoVenda (
  ID_Servico INT NOT NULL,
  ID_Venda INT NOT NULL,
  Quantidade INT NOT NULL,
  INDEX IDVenda_idx (ID_Venda ASC),
  INDEX IDServico_idx (ID_Servico ASC),
  CONSTRAINT IDVenda
    FOREIGN KEY (ID_Venda)
    REFERENCES Venda (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT IDServico
    FOREIGN KEY (ID_Servico)
    REFERENCES Servico (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

